Lesson2
AlekseiSychev/lesson1 pull request #4
Opened 2021-02-28 16:55 UTC by AlekseiSychev

Задания второй недели

2021-03-02 07:49 UTC, IvanMaz requested changes

2021-03-02 07:49 UTC, IvanMaz commented on 1_if1.py
> +def main():
Обычно стандартная структура немного другая - функции описываются вне main, а в main вызываются (объявлять функции внутри функций, конечно можно, но лучше делать это там, где уместно)
```
def age_enter():
    ...

def age_check():
    ...

def main():
    ...
```

2021-03-02 07:49 UTC, IvanMaz commented on 1_if1.py
> +  def age_check():
как раз из-за того, что у тебя все внутри main, у тебя получилась нерабочая функция
формально все запустится, но у тебя функция берет переменную age не из параметров, а из main, потому что ее видит
Надо передавать параметр

2021-03-02 07:49 UTC, IvanMaz commented on 2_if2.py
> +              if len(Line1) == len(Line2):
Сверься с условием задачи)

2021-03-02 07:49 UTC, IvanMaz commented on 2_if2.py
> +          else:
На всякий случай уточню, что тут тоже можно через elif

2021-03-02 07:49 UTC, IvanMaz commented on 3_for.py
> +  avg_sum_school = sum_scores_all_class / len(score_different_clases)
Такой способ подсчета среднего сработает только если во всех классах одинаковое число учеников.
Тебе надо составить один большой список оценок
Воспользуйся тем, что сумма двух списков это их конкатенация

2021-03-02 07:49 UTC, IvanMaz commented on 5_while2.py
> +      for question in questions_and_answers.keys():
чтобы проверить, есть ли элемент в словаре, достаточно сделать ```if smth in my_dict:```

2021-03-02 07:49 UTC, IvanMaz commented on 5_while2.py
> +              print(questions_and_answers[f'{question}'])
кажется, что `f'{question}'` лишнее)
у тебя есть `user_say ` и это строка, можно было воспользоваться ей
также `question` это ключ из словаря, соответственно, если у тебя в словаре ключи строки - это лишнее преобразование, если не строки, то ключ не подойдет

2021-03-02 07:49 UTC, IvanMaz commented on 7_exception2.py
> +        return 'Слишком большая максимальная скидка'
если у тебя скидка больше положенного, то надо поднять исключение ValueError

2021-03-02 07:49 UTC, IvanMaz commented on 8_ephem_bot.py
> +    for x in planet_list:  # Проверка на наличие введенной планеты в списке доступных
со списком - как со словарем
`if smth in my_list`

2021-03-02 07:49 UTC, IvanMaz commented on 8_ephem_bot.py
> +            wrong_name_planet = x # Перезапись переменной на название прошедшей проверку планеты
Вот так делать не очень хорошо, имя переменной должно отражать ее суть
Потому что, когда читаешь код, через 20 строк уже забудешь, что у тебя в переменной "неправильное имя планеты" лежит правильное имя

2021-03-02 07:49 UTC, IvanMaz commented on 8_ephem_bot.py
> +        planet_final = planet(date_str) # Подготовка переменной для constellation. date_str - текущее время
А если у тебя бот работает уже неделю, какая тут будет дата?)

2021-03-13 20:30 UTC, AlekseiSychev commented on 8_ephem_bot.py
> +        planet_final = planet(date_str) # Подготовка переменной для constellation. date_str - текущее время
Как я понял, если перенесу запрос текущего времени (date_str) в функцию, где она используется, то дата будет обновляться при каждом вызове функции, верно?

2021-03-24 10:40 UTC, IvanMaz approved these changes

2021-03-24 11:23 UTC, merged